# Enhanced logging configuration for AI Agent
# This file provides examples of different logging configurations with improved error handling

# Basic configuration
basic:
  log_level: INFO
  enable_file_logging: true
  enable_json_logging: false
  log_dir: logs
  max_log_size_mb: 10
  log_backup_count: 5
  enable_performance_monitoring: true
  enable_health_monitoring: true

# Development configuration
development:
  log_level: DEBUG
  enable_file_logging: true
  enable_json_logging: false
  log_dir: logs/dev
  max_log_size_mb: 5
  log_backup_count: 3
  enable_colors: true

# Production configuration
production:
  log_level: INFO
  enable_file_logging: true
  enable_json_logging: true
  log_dir: /var/log/ai-agent
  max_log_size_mb: 50
  log_backup_count: 10
  enable_colors: false

# Testing configuration
testing:
  log_level: WARNING
  enable_file_logging: false
  enable_json_logging: false
  log_dir: logs/test
  max_log_size_mb: 1
  log_backup_count: 2

# External library log levels
external_loggers:
  chromadb: WARNING
  httpx: WARNING
  urllib3: WARNING
  requests: WARNING
  ollama: INFO
  docker: WARNING

# Enhanced error handling and monitoring
error_handling:
  enable_error_notifications: true
  error_rate_threshold: 10
  error_rate_window_minutes: 5
  max_error_history: 1000

  # Retry configurations
  retry_configs:
    network:
      max_attempts: 3
      base_delay: 1.0
      max_delay: 30.0
      timeout: 30.0
    ollama:
      max_attempts: 5
      base_delay: 2.0
      max_delay: 60.0
      timeout: 120.0
    database:
      max_attempts: 3
      base_delay: 0.5
      max_delay: 10.0
      timeout: 30.0

# Health monitoring settings
health_monitoring:
  enable: true
  check_interval: 60
  thresholds:
    cpu_warning: 80.0
    cpu_critical: 95.0
    memory_warning: 80.0
    memory_critical: 95.0
    disk_warning: 85.0
    disk_critical: 95.0

# Error notification settings (optional integrations)
error_notifications:
  enable_email: false
  enable_slack: false
  enable_webhook: false

  # Email settings (if enabled)
  email:
    smtp_server: smtp.gmail.com
    smtp_port: 587
    username: your-email@gmail.com
    password: your-app-password
    recipients:
      - admin@yourcompany.com

  # Slack settings (if enabled)
  slack:
    webhook_url: https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
    channel: "#alerts"

  # Webhook settings (if enabled)
  webhook:
    url: https://your-monitoring-system.com/webhook
    headers:
      Authorization: Bearer your-token

# Log rotation settings
rotation:
  when: midnight
  interval: 1
  backup_count: 30

# Performance monitoring
performance:
  enable_metrics: true
  slow_operation_threshold: 5.0 # seconds
  memory_usage_threshold: 500 # MB

# Security settings
security:
  mask_sensitive_data: true
  sensitive_fields:
    - password
    - token
    - api_key
    - secret
    - credential
